Squash latest LineageOS commits up to 20.02.2017, 08:00 CET
fs:pstore:ramoops: config mem from dt

configure the start & size of ramoops memory using device tree.

the "dummy" device is no harm as long as initial mem_size is zero.

 Conflicts:
	fs/pstore/ram.c
 Cherry-picked from: bc4df1ea67057fa2117aa6f5b5a967d2ca2cc846

Change-Id: I756e933bea072399cb80ffd78dc79a42b448fed9
Signed-off-by: Yi-wei Zhao <gbjc64@motorola.com>
Reviewed-by: Jeffrey Carlyle <jeff.carlyle@motorola.com>
Signed-off-by: Patrick Tjin <pattjin@google.com>

fs/pstore: initialize pmsg from device tree

- Add pmsg initialization
- or_property_read_u32 does not set *out value if case
  missing. Must initialize _all_ output vars before call.

  Based on: I5c9bcb7bd43af5a80addecf824f14dd7d63b0064

Change-Id: I2723d407be1ae77d45ad5486a2ddd13b82c5c588
Signed-off-by: Patrick Tjin <pattjin@google.com>

pstore: Fix the ramoops module parameters update

In the function ramoops_probe, the console_size, pmsg_size,
ftrace_size may be update because the value is not the power
of two. We should update the module parameter variables
as well so they are visible through /sys/module/ramoops/parameters
correctly.

Change-Id: I18b89758c2e928b29a9e14edecadc80a3c40d8fb
Signed-off-by: Wang Long <long.wanglong@huawei.com>
Acked-by: Mark Salyzyn <salyzyn@android.com>
Acked-by: Kees Cook <keescook@chromium.org>
Signed-off-by: Tony Luck <tony.luck@intel.com>

fs/pstore: fix compilation warning

  fs/pstore/ram.c: In function 'ramoops_probe':
  fs/pstore/ram.c:526:6: error: void value not ignored as it ought to be

Change-Id: I8ad52a8955486df59bb8f7d09757fcb8b1a4e036
Signed-off-by: Patrick Tjin <pattjin@google.com>

ARM: dts: 15801: Configure ramoops memory

 * Buffer start address from stock
 * Sizes from marlin

Change-Id: I6c5ae7c711f41c90f3d7b623e809e11c2b6ba142

ANDROID: sdcardfs: Allow non-owners to touch

This modifies the permission checks in setattr to
allow for non-owners to modify the timestamp of
files to things other than the current time.
This still requires write access, as enforced by
the permission call, but relaxes the requirement
that the caller must be the owner, allowing those
with group permissions to change it as well.

Bug: 11118565
Change-Id: Ied31f0cce2797675c7ef179eeb4e088185adcbad
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: Refactor configfs interface

This refactors the configfs code to be more easily extended.
It will allow additional files to be added easily.

Bug: 34542611
Bug: 34262585
Change-Id: I73c9b0ae5ca7eb27f4ebef3e6807f088b512d539
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: add support for user permission isolation

This allows you to hide the existence of a package from
a user by adding them to an exclude list. If a user
creates that package's folder and is on the exclude list,
they will not see that package's id.

Bug: 34542611
Change-Id: I9eb82e0bf2457d7eb81ee56153b9c7d2f6646323
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: Remove redundant operation

We call get_derived_permission_new unconditionally, so we don't need
to call update_derived_permission_lock, which does the same thing.

Change-Id: I0748100828c6af806da807241a33bf42be614935
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: Add GID Derivation to sdcardfs

This changes sdcardfs to modify the user and group in the
underlying filesystem depending on its usage. Ownership is
set by Android user, and package, as well as if the file is
under obb or cache. Other files can be labeled by extension.
Those values are set via the configfs interace.

To add an entry,
mkdir -p [configfs root]/sdcardfs/extensions/[gid]/[ext]

Bug: 34262585
Change-Id: I4e030ce84f094a678376349b1a96923e5076a0f4
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: switch to full_name_hash and qstr

Use the kernel's string hash function instead of rolling
our own. Additionally, save a bit of calculation by using
the qstr struct in place of strings.

Change-Id: I0bbeb5ec2a9233f40135ad632e6f22c30ffa95c1
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: Switch strcasecmp for internal call

This moves our uses of strcasecmp over to an internal call so we can
easily change implementations later if we so desire. Additionally,
we leverage qstr's where appropriate to save time on comparisons.

Change-Id: I32fdc4fd0cd3b7b735dcfd82f60a2516fd8272a5
Signed-off-by: Daniel Rosenberg <drosen@google.com>

ANDROID: sdcardfs: Fix incorrect hash

This adds back the hash calculation removed as part of
the previous patch, as it is in fact necessary.

Signed-off-by: Daniel Rosenberg <drosen@google.com>
Bug: 35307857
Change-Id: Ie607332bcf2c5d2efdf924e4060ef3f576bf25dc

ANDROID: sdcardfs: Add missing path_put

"ANDROID: sdcardfs: Add GID Derivation to sdcardfs" introduced
an unbalanced pat_get, leading to storage space not being freed
after deleting a file until rebooting. This adds the missing path_put.

Signed-off-by: Daniel Rosenberg <drosen@google.com>
Bug: 34691169
Change-Id: Ia7ef97ec2eca2c555cc06b235715635afc87940e

Revert "input: synaptics: s3320: Actually set BTN_TOOL_FINGER keybit"

 * Duplicated

This reverts commit 5743f2073e6d625d67aafd9e37ce8eb08caca7f2.

Change-Id: I545452400d40bad22d2b433bec17a3aac5690ed7